# Generated by Django 4.2.7 on 2023-11-18 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_image',
            new_name='prof_image',
        ),
    ]
